# Generated by Django 6.0.6 on 2026-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_marqueeitem_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='happy_clients',
            field=models.IntegerField(default=30, help_text='Happy clients counter'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='projects_completed',
            field=models.IntegerField(default=40, help_text='Projects completed counter'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='years_experience',
            field=models.IntegerField(default=5, help_text='Years of experience counter'),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='tagline',
            field=models.CharField(default='3D Creator & Motion Designer', help_text="Short tagline shown below the name (e.g. '3D Creator & Motion Designer')", max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short project description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('3D', '3D & Rendering'), ('Design', 'Design'), ('Dev', 'Development'), ('Motion', 'Motion'), ('Other', 'Other')], default='Other', help_text='Category used for filter tabs in the Skills section', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(blank=True, default='#B501A7', help_text='Accent hex color for progress bar (e.g. #00F0FF)', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, default='✦', help_text='Emoji or short symbol displayed on the skill card (e.g. 🎨, ⚡, 🔥)', max_length=10),
        ),
    ]
