# Generated by Django 6.0.6 on 2026-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contactmessage_aboutsettings_happy_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_image',
            field=models.FileField(blank=True, help_text='Upload an SVG or PNG icon for the floating animation (e.g. Django, Figma)', null=True, upload_to='skills/icons/'),
        ),
    ]
