# Generated by Django 6.0.6 on 2026-07-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Financial Data Analysis', 'Financial Data Analysis'), ('Mobile Development', 'Mobile Development'), ('Full Stack Development', 'Full Stack Development'), ('Design', 'Design'), ('Other', 'Other')], default='Other', help_text='Project category for filtering on the portfolio', max_length=100),
        ),
    ]
