# Generated by Django 6.0.6 on 2026-08-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name shown on the website (e.g. 'Client', 'Personal', 'Mobile Dev')", max_length=100, unique=True)),
                ('icon', models.CharField(default='✦', help_text='Emoji icon shown on the filter tab (e.g. 📊, 📱, 🎨)', max_length=10)),
                ('color', models.CharField(default='#B501A7', help_text='Accent hex color for this category (e.g. #10b981)', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order in filter tabs')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Select a category (manage categories in 'Project Categories')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectcategory'),
        ),
    ]
