# Generated by Django 6.0.6 on 2026-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projectcategory_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(default='body33768@gmail.com', help_text='Every new contact message will be emailed to this address.', max_length=254)),
                ('email_sender_name', models.CharField(default='Portfolio Contact Form', help_text="The 'From' name shown in the notification email.", max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
